leil-io/saunafs

README.md
Special link was generated which allows people
to be automatically invited to workspace.
=> Fix slack workspace link

src/cgi/sfs.css
CSS improvements for the monitoring.
=> cgi: Update sfs.css

tests/test_suites/Benchmarks/test_basic_performance_estimation.sh
This commit adds a very basic write/read speed estimation using dd. The idea is to use it to compare if the performance was affected by changes introduced in code.
=> tests: Add basic performance benchmark

tests/ci_build/setup-test-machine.sh, tests/test_suites/LongSystemTests/test_build_and_rsync.sh, tests/test_suites/LongSystemTests/test_build_saunafs.sh, tests/test_suites/LongSystemTests/test_build_while_auto_recovery.sh, tests/test_suites/LongSystemTests/test_build_while_changing_master.sh
- Update the repository path.
- Add disks to setup script for Long tests that requieres 8 disks to run.
=> tests: Fix long tests to build project

src/mount/writedata.cc
Currently the test_nfs_ganesha_multi_export is failing. The solution was
to keep the write data cache inodedata maxfleng a while longer and
update it also during truncates: test was failing due to master not
having the correct size while the client already dropped their cached
size (the inodedata's maxfleng). Thus, keeping it some extra time should
suffice.
For now, it seems that it fixes the test_nfs_ganesha_multi_export, and passes the SanityChecks, Ganesha test suite and ShortSystemTests.
=> mount: Fix Ganesha multi_export test

doc/sfsmount.1.adoc
Document a feature introduced in 8806a67
=> chore(doc): Add missing option

.editorconfig
- Add markdown section as required to allow linebreak  
(see https://www.markdownguide.org/basic-syntax/#line-breaks).
- Fix a mising dot in .h.
- Add more C/C++ file extensions.
- Sort section properties for easier comparison in later commits.
- Comment each section purpose
=> style: Update the .editorconfig file

NEWS, debian/changelog, utils/update_news.sh
* Add tool for updating both, so you need to only write it once.
* Fix date in previous NEWS entry
=> chore: Update NEWS and debian/changelog

NEWS, debian/changelog, tests/tools/saunafsXX.sh
Apply existing 'main' changes not yet in 'dev'.
=> fix: Reconcile main and dev branches

src/chunkserver/chunkserver-common/disk_interface.h, src/chunkserver/chunkserver-common/disk_manager_interface.h, src/chunkserver/chunkserver-common/hdd_utils.h, src/chunkserver/default_disk_manager.cc, src/chunkserver/default_disk_manager.h, src/chunkserver/hddspacemgr.cc, src/chunkserver/plugin_manager.cc, src/chunkserver/plugin_manager.h
This PR adds the IDiskManager interface and the extensions to the PluginManager to load plugins not based in DiskPlugin (like disk manager plugins).
=> feat(chunkserver): Add disk manager interface

src/mount/fuse/mount_config.cc
This change improves readability of current
mount possible options.
=> fix(mount): help display format

tests/tools/saunafs.sh
This change extends the testing framework to support custom sfshdd.cfg content directly from the tests. For example, to set the content for the chunkserver with index 3, provide the following line before calling the setup_local_empty_saunafs function:
CHUNKSERVER3_HDD_CONTENT="YOUR CUSTOM HDD CONTENT HERE"
This feature facilitates testing of new sfshdd formats and adds flexibility for tests like faking broken drives or using existing real devices.
The existing function 'create_sfshdd_cfg_' was also modified to only create the content. 'create_emulated_zoned_devices_for_cs_number_' will handle now the emulated devices creation, which is more consistent with their names.
=> feat(tests): Allow custom sfshdd content in tests

src/chunkserver/chunkserver-common/default_disk_manager.h, src/chunkserver/chunkserver-common/disk_manager_interface.h, src/chunkserver/hddspacemgr.cc
This change adds two new abstract functions to IDiskManager, to increase the flexibility for the plugins.
=> feat: Extend IDiskManager interface

NEWS, debian/changelog
saunafs (4.5.0) stable; urgency=medium
* fix(mount): Set default cacheExpirationTime to 0 (#180)
* feat(mount): Add readcachemaxsize option (#145)
* feat(master): Add empty reserved files option (#176)
* fix(mount): Fix random case option parsing (#135)
* feat(chunkserver): Add IDiskManager::getDiskForGC (#169)
* test: Improve `stop_ganesha()` function (#168)
* fix(ci): Modify timeout from env (#165)
* ci: Fix tests behavior (#172)
* fix(uraft): Fix missing floating ip address
* fix(mount): Fix create time (Windows) (#167)
* feat(admin): Add list-disk-groups command (#155)
* ci: Abort previous concurrent tests
* ci: Update de base docker image on build
* fix(tests): Fix typo in setup-machine script
* fix(tests): Amend upgrade tests (#146)
* fix: Update services to wait for network (#151) …
=> chore: Changelog for v4.5.0

src/cgi/sfs.cgi.in
- A buggy implementation of sort algorithm was placing last entry as first one.
=> fix(cgi): Change key to re-order list of disks

src/master/exports.cc, src/master/filesystem_checksum.cc, src/master/filesystem_dump.cc, src/master/filesystem_node.cc, src/master/filesystem_node_types.h, src/master/filesystem_operations.cc, src/master/filesystem_store.cc, src/master/hstring.h, src/protocol/SFSCommunication.h, tests/test_suites/ShortSystemTests/test_case_insensitive_filesystem.sh
To align our system with the standard of the Windows file systems, this commits adds necessary dependencies for case insensitiveness option on master server for integration with our system.
=> feat(master): Add case insensitiveness on system

src/chunkserver/chunkserver_entry.cc, src/chunkserver/chunkserver_entry.h
The memory for write operations is now aligned to 4 KiB, which allows to later implement disks writes in DirectIO. It also benefits SMR writes by removing the need of memcpy to align the buffer with the underlying drive block size.
The previous approach was also resizing constantly the vector PacketStruct::packet, which implies frequent allocations. The new PacketStruct::alignedBuffer is now reused most of the time without constant allocations.
=> feat(chunkserver): Use aligned memory for writes

README.md
`git clone https://github.com/leil-io/saunafs.github` -> `git clone https://github.com/leil-io/saunafs.git`
=> Update README.md trivial typo fix

src/chunkserver/bgjobs.cc
Straighforward replacement of remaining pthread_mutex_t in jobpool. The change aims for simpler and safer code (RAII).
=> fix(chunkserver): Replace pthread_mutex_t by std in jobpool

src/metarestore/main.cc
Previously, the logging wasn't working due to changes in the logging code.
=> fix: metarestore logging
