CMakeLists.txt
Clangd and vscode rely on this file to understand the build context of each file in the project. This commit adds the option to easily generate it. The option is enabled by default.
To properly work, the file should be in the root of the repository. At this point, a manual soft link should be generated, pointing to the actual file (cmake_build_directory/compile_commands.json).
=> all: Add option to generate compile_commands.json

src/admin/dump_config_command.cc, src/admin/dump_config_command.h, tests/test_suites/ShortSystemTests/test_admin_dump_config.sh
Previous iteration of the configuration dumping command did not allow dumping default values of services, since default values are set by the caller to the cfg_get* functions, thus there being no single truth to these option values or even names.
This commit adds maps of the currently known configuration options, and the dump-config command uses these to figure out what are the defaults for each service.
This is done with best-effort, because this list may become outdated as time goes on and new options are added. Until we have a single source of truth for these options, this will have to do.
=> admin: Add --defaults options

debian/saunafs-common.postinst, rpm/saunafs.spec
The previous limit (10000) in the number of open files (nofile) for user saunafs was too small for two main reasons:
- In the past we had to change this limit on customer side. Some workloads are requesting a big number of open file descriptors at least in the chunkserver side.
- The new SPLIT format for the chunks can double the usage.
This commit increases the limit and makes it base 2.
=> all: Increase the nofile security limits

CMakeLists.txt, src/chunkserver/chunkserver-common/global_shared_resources.h, src/chunkserver/chunkserver-common/hdd_utils.cc, src/chunkserver/chunkserver-common/hdd_utils.h, src/chunkserver/hddspacemgr.cc, src/chunkserver/hddspacemgr.h, src/chunkserver/masterconn.cc
Relocate disk space utilities to chunkserver-common for plugins access.
The main reason for doing this was to enable some important methods from hddspacemgr.cc
to be accessed from new plugins implemented.
- Move methods from `hddspacemgr.cc` to `hdd_utils.cc` for plugin-compatible access.
- Adjust `hddspacemgr.cc` to use the new `hdd_utils.cc` location, ensuring plugin compatibility.
- Prepare `hdd_utils.cc` for plugin support by enhancing modularity and accessibility.
The reallocated methods were:
- `chunkWriteCrc`
- `hddIOEnd`
- `hddIOBegin`
- `hddScansInProgress`
- `hddChunkFindAndLock`
- `hddChunkFindOrCreatePlusLock`
- `hddRecreateChunk`
- `hddDeleteChunkFromRegistry`
Also, deleted code related to defragmentation on `hddTesterThread` from `hddspacemgr.cc`
=> chunkserver: Reallocate methods for plugin reuse

src/chunkserver/init.h, src/common/run_tab.h, src/main/main.cc, src/master/init.h
The initialization behavior, shared between master, metalogger and chunkserver, was written in plain old C. This commit updates the related parts in the code to be more readable in C++. The refactor scope was:
- Remove duplicated code from the init.h files (there are 3 of them).
- Remove dead code (unused macros and includes).
- Replace C-like callbacks by std::function.
- Replace char * by std::string.
- Replace the C style arrays by std::vector.
- Refactor the 'initialize' function to be more readable.
- Document the main ideas.
=> all: Refactor initializations based on runtabs

tests/test_suites/ShortSystemTests/test_probe_info.sh
After Metadata parallel loading (# 15), the metadata server is returning an extra field for symlinks amount inodes to the info command of saunafs-probe tool. This commit fix a functional test checking this tool.
=> tests: Update check on probe info command

src/chunkserver/chunkserver-common/global_shared_resources.h
The static variable gPerformSync was not shared correctly between the chunkserver and the chunkserver-common at runtime. Causing different values from each side.
This commit makes it inline, which also fixes the
ShortSystemTest.test_fsync_eio_in_chunkserver.
The variable gScansInProgress was also changed to be inline to avoid the same issue.
=> chunkserver: Fix global variables visibility

tests/test_suites/ShortSystemTests/test_pread_eio_in_chunkserver_some_disks.sh
The indexes were shifted after the addition of the soft links to the output of the 'saunafs-probe' info command. This commit only changes the indexes to fix the test.
=> tests: Fix pread_eio_in_chunkserver_some_disks

src/master/hstorage_init.cc
The configuration variable USE_BDB_FOR_NAME_STORAGE was used as USE_BDB_NAME_STORAGE in the hstorage_reload function. Causing incorrect error output in some tests.
=> master: Fix usage of USE_BDB_FOR_NAME_STORAGE

src/chunkserver/chunkserver-common/hdd_utils.cc
Looks like, under heavy workloads scenarios, the chunk->condVar() was left in an underterminate state (probably because of std::move in other thread), causing a segfault in the chunkserver side.
This commit makes sure that we still own the lock when the condition variable is signaled.
=> chunkserver: Fix test_advanced_readahead_params

src/mount/mastercomm.cc, src/protocol/SFSCommunication.h
In commit 488ee3e, fs_connect contained a procedure to send client configuration, however this used fs_send_custom, which used fs_threc_flush that locks the FD. While this is fine when initially connecting, it causes problems when fs_receive_thread tries to create a new session when reconnecting, because it also locks the FD, causing undefined behaviour. This commit fixes this by bringing the function out of fs_connect, and unlocking the FD before calling the configuration function, and then locking it again. This fixes a lot of tests (see below for a list).
Also fixes an error in SFSCommunication.h introduced in the commit, which was noticed while fixing this issue.
Tests fixed:
* ShortSystemTests.test_metadata_recovery
* ShortSystemTests.test_multiple_master_promotions
* …
=> mount: Fix UB when clients reconnect

tests/test_suites/ShortSystemTests/test_shadow_reject.sh
The calls to tape server were removed. We dropped support for it in commit: 344ff92e4da8147e98c59fecff3cb7ac7cb0e850.
=> tests: Fix test_shadow_reject

tests/test_suites/ShortSystemTests/test_cgi_validate_html.sh
The test didn't pass, since it prints a lot of warnings about unescaped ampersands in URLs. We don't really care about this, since we want to replace the CGI for monitoring, so we only check for tracebacks.
=> tests: Disable HTML tidy test

CMakeLists.txt, tests/test_suites/ShortSystemTests/test_saunafs_upgrade_general.sh, tests/tools/saunafs.sh, tests/tools/saunafsXX.sh
This test was problematic for a number reasons, from broken links and version tags to incompatible versions to recursive bash calls (that almost crashed my VM) to shadow not connecting to master.
First was broken links. While this was generally easy to fix, previous LizardFS (rightly) did not include build information in the package versions. Including this information is problematic for both the script (which works around for the moment) and the user, since they both need to find the build information when downgrading, which is not standard behaviour expected of Debian packages.
Second problem was incompatible version changes. It seems that #15 (thanks @lgsilva3087 for pointing me towards this) broke the expected behaviour of `saunafs-admin info` command, so older clients couldn't parse …
=> tests: Fix upgrade_general test

src/mount/direntry_cache.h, src/mount/direntry_cache_unittest.cc, src/mount/sauna_client.cc
Client was not caching any coming data from master after succeeding in the lookup and getattr syscalls. This behavior may cause to issue extra requests to master for no good reason as that data can be cached.
To get it done, inserting single entry without full info (parent inode, name, index and next index) to the DirEntryCache must be implemented and therefore, untie its inner lookup and index sets.
This change is specially important in reducing the amount of lookup requests from Windows client to master server, with  huge impact in the small files read/write issue and performance of many other operations.
=> mount: Extend DirEntryCache to save requests to master

src/mount/direntry_cache.h, src/mount/sauna_client.cc
Our current dev branch is not passing our tests because it is failing on some Ganesha tests. This PR fixes those tests and also some  ShortSystemTests that were failing.
The errors that caused the various failures were introduced while merging the extend-dircache branch, therefore the fixes are related to its behavior.
=> fix: Fix DirEntryCache behavior

CMakeLists.txt, src/chunkserver/chunkserver-common/hdd_utils.cc, src/chunkserver/cmr_disk.cc, src/chunkserver/hddspacemgr.cc, src/devtools/TracePrinter.h
Some of the calls to the traces macros were not updated in previous commits. This change fixes the building by updating these calls with correct parameters and extends the TracePrinter to optionally output to our usual syslog.
To use the traces, just enable the option ENABLE_TRACES in the cmake call. By default it prints to stdout, so, to print to the syslog, the option ENABLE_SYSLOG_FOR_TRACES must be enabled too (useful when running the tests).
To disable the traces for specific modules, add the following line in the module cmake file:
remove_definitions(-DENABLE_SYSLOG_FOR_TRACES)
=> all: Fix build under ENABLE_TRACES

tests/test_suites/SanityChecks/test_metadata_checker.sh
The test was failing by having wrong argument to the setfacl command.
=> tests: Fix metadata ACL tests

src/mount/special_inode.h, src/mount/special_read.cc, src/mount/special_release.cc, tests/tools/saunafs.sh
Attempting to update the value of a variable from the `.saunafs_tweaks` file under some Windows machines has been unsuccessful due to a read operation being executed after the corresponding write operation. This resulted in the changes from the write operation not being reflected because the `getAllValues` function, which resets the `.saunafs_tweaks` values to their defaults and did not check if a write operation had been executed.
This issue was resolved by adding a check in the read operation function related to `.saunafs_tweaks`. If the file had been written to, a procedure is initiated that constructs the expected string format and applies the correct update operation on the `.saunafs_tweaks` data, according to the format of the input from PowerShell commands.
=> mount (win): Fix .saunafs_tweaks behavior

src/common/small_vector.h
The compiler was complaining with free-nonheap-object warning on insertion method for the small_vector ADT. This commit replaces the implementation with the one from boost::container library.
=> fix(common): Change small_vector implementation

src/mount/tweaks.cc, src/mount/tweaks.h, tests/ci_build/run-build.sh
A typo at CMAKE_BUILD_TYPE made the cmake to build the code in Debug mode by default. This was making a segFault error pass un-detected because linkage modification introduced at PR#19.
=> ci, mount: Fix segFault on libsaunafsmount_shared

debian/control
* Add a missing build dependancy
* Remove Conflicts/Replaces/Provides. These were leftovers from LizardFS that ensured MooseFS and LizardFS could not be installed at the same time (since they shared executable names). We don't need this anymore since all the names have changed, and the sfs was a little confusing due to the rename, which probably delayed people from noticing this.
=> tidy(debian): Cleanup control file

tests/test_suites/TestTemplates/test_saunafs_upgrade_overwrite_file.inc, tests/test_suites/TestTemplates/test_saunafs_upgrade_undergoal_chunks.inc, tests/tools/saunafsXX.sh
This is a series of 2 commits squashed:
fix(tests): Upgrade tests on freshly installed machines
This commit fixes an issue from earlier regarding updates to setup_machine.sh. Now that the SaunaFS key is acquired from the setup_machine.sh script and it adds the repository, there is no need to add a source to the script when doing upgrade tests. Doing so would conflict with the already setup repository
fix(tests): Long upgrade tests
* Fix no old version checking by using latest client instead.
* Fix recursion bug by not using sfs* tools, instead using saunafs
=> fix(tests): Upgrade tests

tests/run-test.sh, tests/setup_machine.sh, tests/tools/assert.sh, tests/tools/test.sh
This is a series of 3 commits:
tidy(tests): Remove unnecessary ticks
This messes up some editor syntax highlighting
fix(tests): Fix binary output being outputted
The variable used in the conditional is different from the actual
filename used. This conditional would always succeed since awk would
return 0 if the conditional in awk would not match, which it didn't
since stdout was empty (only stderr was populated with the error
message, but it is disregarded).
fix(tests): Coredumps not being generated
At least 3 years ago, `sudo` had a change of behaviour regarding
coredumps. This fixes that by setting the default for cores as the
system.
=> fix(tests): Various fixes for the testing framework 

.dockerignore
.dockerignore allows docker images building from the source context to ignore files, including build files and .git, which can balloon the context and significantly slow down image build times. The file is very similar to .gitignore, with minor changes specific for docker
On that note, .gitignore has been updated to not include files that are made by setup_machine.sh, and its aesthetics has been tidied up.
=> chore(.gitignore): Add .dockerignore and update .gitignore

.clang-tidy
clang-tidy is similar to cppcheck, but it is more powerful and has a greater amount of diagnostics, particulary regarding idiomatic C++. It can be used in conjunction with cppcheck in both editors and potentially the CI. I've been personally using this file for a few months now, tweaking it to suppress unwanted diagnostics, and I believe it is good enough to warrant inclusion.
=> chore: Add .clang-tidy

src/chunkserver/hddspacemgr.cc, src/mount/chunk_locator.h, src/mount/chunk_writer.cc, src/mount/chunk_writer.h, src/mount/sauna_client.cc, src/mount/writedata.cc, src/mount/writedata.h, tests/test_suites/ShortSystemTests/test_ec_truncate_atomicity.sh, tests/test_suites/ShortSystemTests/test_no_reads_during_small_ec_files_write.sh, tests/test_suites/ShortSystemTests/test_reads_during_small_ec_files_write_parallel.sh
Tests performed show that during EC writes the client connects and asks
to the chunkservers for the missing data parts of the current stripe,
which are the data parts the client are not writing. This is required if
the file is bigger than the last byte it is writing, but it should not
ask for data on offsets beyond the file size. It is specially important
for the writings of small files, and removing those extra requests
should reduce overhead.
Current solution manages to calculate chunkSizeInBlocks_ for each
ChunkWriter at the moment of initialization from the field maxfleng of
the current inode's inodedata. Thus, the maxfleng field should be
updated the best way possible. The chunkSizeInBlocks_ is then used to
check if client ws about to was to chunkservers for not existing data.
=> mount: Reduce readings during ec write

src/common/small_vector.h, src/uraft/uraft.h
When using cmake flag RelWithDebInfo using gcc version 13 two issues arise:
- common: the small_vector template raises the Werror=stringop-overflow so compiler is instructed to ignore this warning until a proper fix can be applied.
- uraft: boost::asio std::exchange is not found.
=> all: Apply fix to build using gcc-13 on release

CONTRIBUTING.md, README.md
Previously we said we won't accept outside and while the policy hasn't changed per-se, changing this policy isn't a priority anymore. To not discourage people from submitting code, the files are updated state to contact us before contributing any code to us, so we have time to respond and work out the necesarry details needed to accept the code.
Fix a empty link in README.md as well.
Closes #8
=> chore: Update CONTRIBUTING.md and README.md

INSTALL.md
Follow-up to commit 806603a, this adds instructions for 22.04 and fixes a mistake with the codename still being jammy.
=> chore(INSTALL.md): Include instructions for Ubuntu 22.04

src/tools/recursive_remove.cc
`char` is unsigned on ARM64, versus signed on x86. This causes a warning on ARM64 platforms in the condition below, because `ch` can never be -1 if it's on an ARM64. This fixes that by using int instead, like elsewhere in the tools directory.
Closes #70
=> fix(tools): ARM64 compilation on Linux

doc/sfsmount.1.adoc
Document the options introduced to tune the client new read algorithm.
=> chore(doc): Document missing options

src/chunkserver/bgjobs.cc, src/chunkserver/hddspacemgr.cc, src/chunkserver/network_worker_thread.cc
This change renames the chunkserver threads to better identify them at runtime. It is useful for debugging and profiling purposes.
Note: thread names can be up to 16 characters.
=> chunkserver: Add thread names

src/chunkserver/buffers_pool.h
The check for buffers_.empty() was not protected, causing segmentation fault when multiple NetworkWorkers were configured.
The queue max size (kMaxSize) was also increased by 8, to better support heavy workloads.
=> chunkserver: Fix race condition in BuffersPool

tests/test_suites/GaneshaTests/test_nfs_ganesha_file_corruption_on_master_failover.sh
This commit adds an integration test to detect whether there is file corruption during master fail over. This test is based on issue #68 of SaunaFS reported by Sarkans team.
Basically, the test copies a 3Gb file through NFS mount and restarts the master server during the process. After copying the file, checksum of the file is verified twice: first, reading the file through NFS mount and second, reading the file through SaunaFS mount.
=> test: Add Ganesha test for validating file corruption

tests/ci_build/ganesha/Dockerfile, tests/setup_machine.sh
Previously, for building Ganesha there were included some FSALs like CEPH, GLUSTER and RGW that are enabled by default. It added extra dependencies not needed by SaunaFS that can be removed after disabling not needed FSALs.
This commit removes additional dependencies introduced by Ganesha. By removing these dependencies, SaunaFS installation will take less space and time.
The list of removed dependencies is:
- ceph, libcephfs-dev, libglusterfs-dev, librgw-dev, xfslibs-dev
It was also added libnsl dependency, that is needed by libntirpc library when building Ganesha in Ubuntu 24.04.
=> tests,ci: Remove Ganesha unneeded dependencies

src/admin/main.cc
The previous implementation of saunafs-admin was failing on Windows environment when trying to connect to an specific master server instance due to not correctly initializing the socket communication for Windows. This commit fixes that issue.
=> fix(saunafs-admin): Fix saunafs-admin for windows

src/mount/direntry_cache.h, src/mount/direntry_cache_unittest.cc, src/mount/sauna_client.cc, tests/test_suites/ShortSystemTests/test_direntrycache_checks.sh
This PR includes the following:
- a new test: test_dircache_checks. It is included in the ShortSystemTests test suite for now and attempts to cover most of the syscalls which has something to do with the DirEntryCache.
- two more tests for the DirEntryCache unittests covering latest changes.
- fixes in the DirEntryCache behavior
=> mount, tests: Improve DirEntryCache scenarios coverage

src/common/chunk_copies_calculator.cc, src/common/chunk_copies_calculator.h, src/common/linear_assignment_cache.h, src/common/linear_assignment_cache_unittest.cc, src/data/sfsmaster.cfg.in, src/master/chunks.cc
It was found that the slices list was not properly updated with the result of the auction algorithm and separately some tests showed high CPU usages in idle master specially in the ```optimize``` and ```auctionStep``` functions.
This pull request attempts to fix those issues and proposes these changes:
- apply result of the auction optimization algorithm in the optimize function.
- cache already calculated values in this function to avoid recalculating them again.
- try to skip as much as possible unnecessary computing.
- add option to directly disable these computations.
=> common, master: Auction optimization related improvements

src/mount/mastercomm.cc, src/mount/mastercomm.h, src/mount/sauna_client.cc, src/mount/sauna_client.h
When master server disconnected, windows client
was unable to be used and the process terminated.
With this change is its possible to the windows
client to know when master is disconnected and
make the mountpoint still accessible.
=> Fix mount when master down

src/chunkserver/hddspacemgr.cc, src/chunkserver/plugin_manager.cc
The previous mesages were shown as warnings, but is normal to not have plugins to load. This commit uses less severe messages in the plugin loading sections.
=> fix(chunkserver): Improve plugin related logs

tests/tools/test.sh
Previously, after running the tests, used space was not cleaned because the path for disks and loop devices was not correctly setup. Therefore, the used space by the tests needed to be cleaned manually to avoid the disks become full.
This commit updates the path for disks and loop devices including data and meta folders. Consequently, the space used by the tests is now cleaned up correctly.
=> tests: Clean up space used by the tests

src/mount/mastercomm.cc
In the previous implementation, the client was not properly working when
the master server was restarted and first getattr operations where
executed on Windows. This change makes the mount to first try to
properly reconnect to master and if not, directly assume no data was
received from master, thus avoid the mount process to crash when
trying to use the mountpoint.
=> fix(mount): Fix Windows master connection checking

src/admin/dump_config_command.cc
The recently added ```USE_LINEAR_ASSIGNMENT_OPTIMIZER``` option to master server was missing in the list of master default options, and should be shown there.
=>  admin: Add USE_LINEAR_ASSIGNMENT_OPTIMIZER to master default config

.gitignore
The submodule directories should be ignored in saunafs.
=> chore: Ignore the ICE submodule

tests/tools/saunafs.sh
The test could sometimes fail due to a invalid default host (perhaps because there is already a mount on the server for another host). This change makes it explicit to use localhost as the host name.
=> fix(tests): Fix test_cgi_validate_html test

src/errors/sfserr.cc
In some configurations, the compiler does not find the std string header automatically. This commit just adds the header to avoid these scenarios.
=> fix(errors): Add explicit std string include

src/chunkserver/chunkserver-common/global_shared_resources.h, src/chunkserver/hddspacemgr.cc, src/chunkserver/hddspacemgr.h, src/chunkserver/init.h, src/data/sfschunkserver.cfg.in
This change exposes the gDiskManager to the plugins by moving it to the chunkserver-common library. The DISK_MANAGER_TYPE configuration variable was also added to select the specific disk manager to use at run time.
=> feat(chunkserver): Expose gDiskManager to plugins

src/mount/fuse/mount_config.cc
This PR fixes the format of the ```sfscacheperinodepercentage```
option in the help message.
=> fuse: Fix sfscacheperinodepercentage help

src/chunkserver/hddspacemgr.cc, src/common/cfg.cc, src/common/cfg.h, src/common/cfg_unittest.cc
The previous version was completely implemented from the scratch. The proposed version uses modern C++ and std::stod to increase readability and safety. The commit makes it also more flexible with different suffixes for the size and improves the error handling.
The function initially was in the hddspacemgr.cc in the chunkserver, but it is very general and will be used from the plugins soon, so it makes sense to move it to the common library.
An unit test file was also added to verify different combinations.
=> feat(common): Improve the hddSizeParse function

cmake/Packing.cmake
The content of file cmake/Packing.cmake was producing a syntax warning during fresh installation due to a syntax issue, this commit solves that.
=> fix(build): Fix cmake syntax warning

src/chunkserver/chunkserver-common/default_disk_manager.cc, src/chunkserver/chunkserver-common/default_disk_manager.h, src/chunkserver/chunkserver-common/disk_manager_interface.h, src/chunkserver/hddspacemgr.cc
The functions based on IDiskManager::getDiskForNewChunk now accept a ChunkPartType as argument, to allow disk assignments based on the this type. The default implementation does not use it yet, but it is needed for the plugins.
=> feat(chunkserver): Extend getDiskForNewChunk

tests/test_suites/GaneshaTests/test_nfs_ganesha_client_io_error_on_master_kill.sh
For some scenarios, where the master server is restarted during IO operations, nfs mount can become unavailable and IO operations using nfs mount return Input/Output error.
This commit adds an integration test to detect file corruption in IO operations using nfs mount during master fail over. This test is based on issue #68 of SaunaFS reported by Sarkans team.
The test copy a 3Gb file through NFS mount while restarting the master server during the process. After copying the file, checksum of original and copied files is verified to validate there was not file corruption during the process.
=> tests: Add Ganesha test for master failover

rpm/service-files/saunafs-uraft.service
Current saunafs-uarft binary is deploying a service file `saunafs-uraft.service` that if service fails, it doesn't allow to be automatically reloaded.
=> Fix service uraft restart on failure

rpm/service-files/saunafs-cgiserv.service, rpm/service-files/saunafs-chunkserver.service, rpm/service-files/saunafs-ha-master.service, rpm/service-files/saunafs-master.service, rpm/service-files/saunafs-metalogger.service, rpm/service-files/saunafs-uraft.service
network.target is not giving warranty that IP addresses are set
network-online.target gives such assurances
https://systemd.io/NETWORK_ONLINE/
Co-authored-by: Antuan <antuan@leil.io>
Co-authored-by: Crash <crash@leil.io>
=> fix: Update services to wait for network

src/common/metadata.cc, src/common/metadata.h, src/master/filesystem.cc, src/master/filesystem_store.cc, src/master/matoclserv.cc, tests/test_suites/ShortSystemTests/test_metadata_load_legacy.sh
The master server now loads legacy metadata `mfs` if no actual metadata is found. This allows easy migration from legacy systems where metadata is store in legacy format. Shadow server also can download legacy metadata and convert it to new format after service is restarted or dump is trigger by admin tool. Loading of actual metadata takes precedence over legacy and if both are present, actual is loaded instead and user is warned to delete legacy.
=> feat: Allow master to load legacy metadata

tests/ci_build/run-ganesha-tests.sh, tests/ci_build/run-sanity-check.sh, tests/saunafs-tests.cc
When the binary for tests was moved to a different path it could not find the tests bash script. 
This commit adds an environment variable to allow the path change in run time.
=> fix(tests): Allow to change tests data path

src/mount/sauna_client.cc, src/mount/sauna_client.h
This PR aims to provide the expected behavior of our system while
dealing with the IIS tool. This tool apparently uses a very specific
user (17) to access the underlaying files. The user 17 was not expected
to perform these kinds of operations, thus causing the permission denied
errors. Solution was to make a breach at some checks to allow it.
=> fix(mount): Fix IIS permissions mess

src/admin/list_disk_groups_command.cc, src/admin/list_disk_groups_command.h, src/admin/main.cc, src/chunkserver/chunkserver-common/default_disk_manager.h, src/chunkserver/chunkserver-common/disk_manager_interface.h, src/chunkserver/hddspacemgr.cc, src/chunkserver/hddspacemgr.h, src/chunkserver/network_worker_thread.cc, src/protocol/SFSCommunication.h
The saunafs-admin was extended to show the disk groups configuration from the chunkservers. The default disk manager does not support this feature yet and prints 'Not supported', but it is already available (and used) from the plugins by reimplementing the default behavior.
=> feat(admin): Add list-disk-groups command

src/common/stat32.h, src/mount/sauna_client.cc
The create time in Windows is got from the ```st_birthtime``` field,
therefore that field must be filled from the ```ctime``` field and
passed to the next layers.
=> fix(mount): Fix create time (Windows)

src/uraft/main.cc, src/uraft/saunafs-uraft-helper.in, src/uraft/uraftcontroller.h
If something removes the floating ip address from the device, saunafs-uraft will not bring it back. For example, on Ubuntu systems, if systemd-networkd is restarted, it will reapply netplan config, which inadvertently remove the floating ip address, and uraft has no way of adding this back.
This fix adds a way for uraft to bring the IP address back. First by exporting the IP address as an environment variable in the main program, and then by using in the script to query iproute2 for the IP address, and add it when it's missing.
Note that if two IP addresses with different subnet masks are added, then it won't re-add the IP address with the correct subnet mask.
=> fix(uraft): Fix missing floating ip address

src/chunkserver/chunkserver-common/default_disk_manager.cc, src/chunkserver/chunkserver-common/default_disk_manager.h, src/chunkserver/chunkserver-common/disk_manager_interface.h, src/common/unique_queue.h
This commit adds and extension point for the disk managers to be asked about the next disk for garbage collection (GC). The default disk manager returns the next zoned device in a round-robin approach.
It is up to the disk manager plugins to provide custom implementation for this behavior.
=> feat(chunkserver): Add IDiskManager::getDiskForGC

doc/sfsmount.1.adoc, src/data/sfsmaster.cfg.in, src/master/filesystem.cc, src/master/filesystem_periodic.cc, src/master/filesystem_periodic.h, tests/test_suites/ShortSystemTests/test_create_empty_reserved_files.sh
For avoiding reserved files to take system space indefinitely, this change add a periodical empty procedure over reserved files.
=> feat(master): Add empty reserved files option

doc/sfsmount.1.adoc, src/mount/sauna_client.h, tests/test_suites/SanityChecks/test_options_random_casing.sh
This is a temporary mitigation for #179, it does not fix it.
=> fix(mount): Set default cacheExpirationTime to 0

tests/run-test.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_file_corruption_on_master_failover.sh
This test occasionally failed during master failover when the NFS client performed operations like file copy and checksum validation. Additionally, the test previously read from the OS cache instead of the NFS mount, leading to data corruption and mount unavailability.
This commit improves test reliability by increasing `io_retries` for a more robust recovery mechanism in the SaunaFS client. It also extends the grace period and lease lifetime to give Ganesha more time to recover. Finally, reading checksum through NFS was modified to use `dd` with the `iflag=direct` to read the file directly from the disk, bypassing the OS cache and preventing cache-related issues.
=> test: Improve Ganesha test for master failover

tests/setup_machine.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_connectathon_nfs_suite.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_copy_file.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_file_corruption_on_master_failover.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_fio_random_mix_reads_writes.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_fio_random_reads.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_fio_random_writes.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_fio_sequential_mix_reads_writes.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_fio_sequential_reads.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_fio_sequential_writes.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_multi_export.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_vs_linux_client_dd_read.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_vs_linux_client_dd_write.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_vs_linux_client_random_mix_rw.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_vs_linux_client_sequential_read.sh, tests/test_suites/GaneshaTests/test_nfs_ganesha_vs_linux_client_sequential_write.sh, tests/tools/ganesha.sh, tests/tools/test_main.sh
Previously, Ganesha tests failed when RPC became unavailable during the test suite execution. There was also some logic repeated across the suite, such as the creation of Ganesha PID file.
Key changes:
- Introduced a recovery mechanism for the RPC service to handle failures during the test suite execution.
- Refactored the Ganesha PID file creation by encapsulating the logic into a new `create_ganesha_pid_file` function, which is now used across all suite to avoid redundancy.
=> feat(tests): Add RPC service recovery function

src/chunkserver/chunkserver-common/default_disk_manager.cc, src/chunkserver/chunkserver-common/default_disk_manager.h, src/chunkserver/chunkserver-common/disk_manager_interface.h, src/chunkserver/chunkserver-common/global_shared_resources.h, src/chunkserver/hddspacemgr.cc
This commit adds and extension point for the disk managers to be asked about the next chunk to test. The default disk manager uses the same approach as before.
It is up to the disk manager plugins to provide custom implementation for this behavior.
=> feat(chunkserver): Get chunk to test from manager

doc/sfsmount.1.adoc, src/mount/chunk_locator.h, src/mount/chunk_reader.cc, src/mount/chunk_reader.h, src/mount/masterproxy.cc, src/mount/readdata.cc, src/mount/readdata.h, src/mount/readdata_cache.h, src/mount/sauna_client.h, src/mount/writedata.cc, tests/test_suites/SanityChecks/test_options_random_casing.sh, tests/test_suites/ShortSystemTests/test_many_parallel_reads.sh
This PR targets getting rid of race conditions in the client side
with the help of helgring (valgrind suite). Though it does not remove
all of the issues pointed out by helgrind, it does fixes many of them.
This PR also fixes the issue with the many parallel readings, thus 
bringing back the default values of the cacheexpirationtime parameter.
List of changes:
- check the status of the entries in result (ReadCache::Result) before returning
it in the request function.
- rename operations manager mutex to gReadaheadRequestsContainerMutex
and restrict its use to the cases when the container is used.
- add mutex per ReadRecord to protect its readaheadRequests,
readahead_adviser and cache.
- add mutex per read cache's Entry to protect its members, specially
the buffer and the timer.
- fix …
=> fix(mount): Fix client race conditions

.github/workflows/run-ganesha-tests.yml, .github/workflows/run-unit-and-ganesha-tests.yml
Previously, Ganesha and Unit Tests suites ran as part of a Jenkins pipeline.
This commit adds a Github Actions workflow to run Ganesha and Unit Tests suites.
=> ci: Add Github workflow to run Ganesha and Unit Tests

Jenkinsfile
Due to the current large size of the artifacts being build, strict limits must be put in place to not overwhelm the storage of Jenkins.
=> ci: Limit amount of artifacts

src/common/sockets.h, src/mount/mastercomm.cc
When trying to start client connection to master, sometimes error receiving data from master was shown as successful, which is not correct. This change improves readability of error by specifying a type of it when logging error message from client.
=> fix(mount): Fix tcptoread-write error message

.github/workflows/run-unit-and-ganesha-tests.yml
The previous Github Actions workflow in charge of running Ganesha and Unit Tests showed some annoying warnings about using deprecated node versions.
This commit updates versions for `checkout` and `setup-python` actions to remove these warnings.
Key changes:
- Updated `actions/checkout` from v2 to v4.
- Updated `actions/setup-python` from v2 to v4.
=> ci: Update GitHub Actions to use latest versions

src/chunkserver/network_worker_thread.cc, src/chunkserver/network_worker_thread.h
Refactor structures related to NetworkWorker, ChunkserverEntry and PacketStruct.
The refactoring aims to:
- Improve readability of this code part.
- Modernize usage of the language.
- Improve type safety.
- Improve documentation.
There are no changes yet in the logic to keep simple this review.
=> Refactor old csserventry related structs

Jenkinsfile
Fixes logs not showing due to a race condition with saunafs-tests reading /var/log/syslog and the file actually being created
https://github.com/leil-io/sfstests/compare/v0.2.0...v0.2.1
=> ci: Update sfstests to v0.2.1

tests/tools/assert.sh, tests/tools/timeout.sh
Some functions were only applying the multiplier if Valgrind was enabled. This fixes that by ensuring it's applied regardless of that
It also applies the multiplier to the default timeout of 15 seconds in assert functions, with it being adjustable through an environment variable.
=> test: Apply multiplier regardless if Valgrind enabled or not

doc/sfsmaster.cfg.5.adoc, src/admin/dump_config_command.cc, src/data/sfsmaster.cfg.in, src/master/matocsserv.cc, tests/test_suites/ShortSystemTests/test_ec_prioritize_data_parts.sh
Originally, the master server was placing the data parts in the chunkservers with higher available space factor. Then, the parity parts were placed in the remaining chunkservers.
If the cluster is not balanced (some chunkservers have more space than others), then almost all parities land in the same chunkservers. This causes that reading is always issued to the chunkservers with data parts, so the chunkservers with parity parts are barely used when reading.
This commit introduces the configuration variable PRIORITIZE_DATA_PARTS to control this behavior. The default value is 1 (active), which is the same as it was before.
=> feat(master): Add option to toggle data parts priority

src/chunkserver/network_worker_thread.cc, src/chunkserver/network_worker_thread.h
Partial refactor of ChunkserverEntry related structs.
Main goals:
- Avoid C-like linked lists and use std::list.
- Simplified memory management (malloc and free was used before).
- Reuse of already allocated memory.
- Use of move semantics.
- Simplified destruction and cleanup.
- Shorter code.
- Remove void* and casts.
=> Refactor chunkserverentry use std list and smart pointers

tests/tools/assert.sh
The previous call was expanding to two arguments, possibly causing non-deterministic errors in some tests.
=> fix(tests): Fix call to timeout_rescale

doc/sfschunkserver.cfg.5.adoc, src/chunkserver/masterconn.cc, src/data/sfschunkserver.cfg.in, tests/test_suites/ShortSystemTests/test_chunkserver_masterconn_workers.sh
Previously the master connection had a fixed amount of 10 worker threads  in the jobs pool. This commit makes it configurable, to be able to adapt it to the expected workload.
For instance, a chunkserver handling a small number of disks may have a lower value.
=> feat(chunkserver): Make configurable masterconn workers

doc/saunafs-uraft-helper.8.adoc, src/uraft/saunafs-uraft-helper.in, src/uraft/uraftcontroller.cc, src/uraft/uraftcontroller.h
Previously, the loss of the uRaft floating IP caused SaunaFS services to stop. Consequently, the cluster was unable to recover and it was required a manual restart of the uraft service to bring back the floating IP.
This commit introduces a recovery mechanism that allows SaunaFS to regain the floating IP after unexpected failures.
The key changes are:
- Added `saunafs_is_floating_ip_present()` in `saunafs-uraft-helper` to check the current state of the floating IP.
- Added `isFloatingIpAlive()` in uRaft to check the floating IP status by invoking a helper script function.
- Introduced logic to demote the current leader if the floating IP is lost and ensure metadata synchronization between shadow servers and the newly elected leader. It avoids having split brain scenarios.
=> feat(uraft): Add mechanism to recover floating IP

doc/sfschunkserver.cfg.5.adoc, doc/sfsmaster.cfg.5.adoc, src/chunkserver/hddspacemgr.cc, src/chunkserver/network_worker_thread.cc, src/common/event_loop.cc, src/common/event_loop.h, src/data/sfschunkserver.cfg.in, src/data/sfsmaster.cfg.in, tests/test_suites/ShortSystemTests/test_poll_timeout.sh
A poll timeout of 50 ms could introduce latency if the events occur more frequently. This commit makes the timeout configurable to easy test with different values to find optimal balance between timeout and CPU usage.
=> feat(master, chukserver): Make poll timeout configurable

src/data/sfsgoals.cfg
* Add more practical EC examples
* Format the file
* Set a space in between the goal name and the colon before definition.
=> docs(sfsgoals.cfg): Give more practical examples

utils/data_generator.h
Current version of the code, when showing the error offset in a
file-validate check many times say a wrong offset inside the file. This
is because it is showing the error offset inside the buffer reading
from the checked file.
The real offset may be obtained from the expected data, but it would be
much easier to show it as a first result.
=> fix: Clarify error offset in file-validate

tests/test_suites/ShortSystemTests/test_read_write_during_scan.sh
This change fixes an issue when executing test_read_write_during_scan from ShortSystemTests because directio option was not available on Windows client options.
=> fix(tests): Fix read-write during scan for Windows

Jenkinsfile, tests/tools/saunafsXX.sh
* Update sfstests to 0.3.0 to use new --auth option
* Change how and where the testing framework looks for auth file
=> ci: Add upgrade tests

src/tools/sfstools.sh, tests/test_suites/SanityChecks/test_sfstools.sh
Fixes https://github.com/lizardfs/lizardfs/issues/886, requested in https://github.com/lizardfs/lizardfs/pull/887#issuecomment-2333801710
This commit is a port of that fix for LizardFS to SaunaFS.
An example error message was:
```console
$ LC_ALL=C bash -x /usr/bin/mfssetgoal --help
++ basename /usr/bin/mfssetgoal
+ tool=mfssetgoal
+ mfssetgoal --help
bash: warning: shell level (1000) too high, resetting to 1
```
=> fix(tools): infinite recursion in sfstools.sh

src/chunkserver/chunkserver-common/global_shared_resources.h, src/chunkserver/chunkserver-common/hdd_utils.cc, src/chunkserver/chunkserver-common/hdd_utils.h, src/chunkserver/hddspacemgr.cc, tests/setup_machine.sh, tests/test_suites/ShortSystemTests/test_chunkserver_advise_no_cache.sh
The option HDD_ADVISE_NO_CACHE was not used. It is now used inside the hddIOEnd function for both, the metadata and data files for each chunk.
Enabling the option in the chunkserver configuration file effectively reduces the page cache size used by the chunkservers, but also could reduce the performance in some scenarios.
=> fix(chunkserver): Use option HDD_ADVISE_NO_CACHE

tests/test_suites/ShortSystemTests/test_read_cache_low_level_percentage.sh, tests/test_suites/ShortSystemTests/test_read_corrupted_files.sh
Changes:
- use tab instead of space for indentation
- make the test_read_cache_low_level_percentage a bit more loose for
Windows testing.
=> tests: Small fixes on read tests

src/mount/sauna_client.cc, src/mount/writedata.cc, tests/test_suites/SanityChecks/test_mount_tweaks.sh
This change allows the users to modify the sfsignoreflush option during runtime execution of the client.
=> feat(mound): Add ignoreflush to tweaks variables

doc/sfsmount.1.adoc, src/mount/fuse/mount_config.cc, src/mount/writedata.cc, tests/test_suites/SanityChecks/test_mount_tweaks.sh, tests/test_suites/ShortSystemTests/test_ignore_flush.sh
This change adds a test for checking the sfsignoreflush option when a possible write process could fail during the flush operation. This way it is possible to check that when sfsignoreflush is on, some writing errors can be ignored.
This PR should be merged after: [#228](https://github.com/leil-io/saunafs/pull/228)
=> test(mount): Add test for ignoreflush option

doc/sfsexports.cfg.5.adoc
The implemented caseinsensitive option for sfsexports files was not given as part of all man documentation as other options from these configuration files. This change adds a basic doc for it.
=> doc(master): Add man docs for caseinsensitive

doc/sfschunkserver.cfg.5.adoc, src/admin/dump_config_command.cc, src/chunkserver/chunkserver-common/cmr_disk.cc, src/chunkserver/chunkserver-common/global_shared_resources.h, src/chunkserver/hddspacemgr.cc, src/data/sfschunkserver.cfg.in, tests/test_suites/ShortSystemTests/test_chunkserver_stat_chunks_at_disk_scan.sh
Scanning disks with millions of chunks can take a considerable time. At scan time, by default, the chunkserver performs an stat operation on the metadata and data files of each chunk. This check is good, but makes the scan process very slow.
This change adds the configuration option STAT_CHUNKS_AT_DISK_SCAN to optionally disable this behavior. The scan time with this option disabled is around 40 times faster.
=> feat(chunkserver): Stat chunks at scan optionally

src/chunkserver/bgjobs.cc, src/common/pcqueue.cc, src/common/pcqueue.h, src/common/pcqueue_unittest.cc, src/mount/writedata.cc
This commit replaces previous C-based pcqueue with a modern PCQueue class to improve resource management and maintainability. This refactor transitions from C-style manual memory management to smart pointers and modern C++ synchronization primitives like `std::condition_variable` and `std::mutex` to ensure thread-safe concurrent access.
=> refactor(common): Replace raw queue with PCQueue

tests/tools/config.sh, tests/tools/saunafs.sh, tests/tools/test.sh, tests/tools/timeout.sh
Changes:
- change comment in timeout.sh to make it more general. Previous
comment was outdated.
- define SAFS_MOUNT_COMMAND also for Windows Client testing, and
substitute the sfsmount3.exe occurences.
- update the sfsmount3.exe for sfsmount.exe, because the Windows Client
CLI binary was renamed like this some time ago.
=> refactor: Minor changes in Windows Client testing

src/common/pcqueue.cc
The `ProducerConsumerQueue` class previously triggered Helgrind warnings due to condition variables being notified (`notify_one()`) without holding the associated mutex. This behavior could result in race conditions and undefined behavior.
This commit ensures that `notEmpty` and `notFull` condition variables are always notified while holding the mutex, guaranteeing thread safety and proper synchronization.
=> fix(pcqueue): Remove Helgrind warnings

src/mount/mastercomm.cc, src/mount/readdata.cc, src/mount/readdata.h, src/mount/readdata_cache.h, src/mount/sauna_client.cc, tests/test_suites/SanityChecks/test_helgrind_basic.sh, tests/tools/valgrind-helgrind.supp, tests/tools/valgrind.sh
The threading safety was not checked explicitely in our tests. Threading issues can cause non-deterministic runtime errors that are hard to reproduce and debug. We use multiple threads so far in the chunkservers and clients.
This change introduces a basic test using helgrind (from valgrind). The idea is to gradually add complexity to this test and create others (more specific) when needed.
Some extra commits were added for already detected warnings.
=> test(all): Add new basic helgrind test

src/mount/acquired_files_last_time_used.h, src/mount/mastercomm.cc, src/mount/mastercomm.h, src/mount/sauna_client.h
This change enables the corresponding options to be used on the Windows client for cleaning open unused files by external applications using our filesystem.
=> feat(mount): Add option for open files on Windows

src/mount/readdata.cc, src/mount/readdata.h, src/mount/readdata_cache.h, src/mount/sauna_client.cc, tests/test_suites/ShortSystemTests/test_read_cache_low_level_parallel_reads.sh
- **test(mount): Add test for multi read low cache**
- Added a test to ensure the system can handle multiple read processes with low read cache memory.
- **feat(mount): Add threads for read records garbage**
- Introduced threads for each active read record to manage their own read cache garbage collection.
- **feat(mount): Add cache expiration time thread**
- Added a thread to dynamically update the read cache expiration time for better handling of multiple parallel reads.
- **feat(mount): Fix window read cache suggested size**
- Adjusted the read ahead window size distribution among read workers to balance the load during multiple parallel reads.
- **feat(mount): Add limitation to extra read requests**
- Disabled additional read requests when read cache memory is almost full to prevent …
=> Fix readcache memory release

src/mount/mastercomm.cc, src/mount/readdata.cc, src/mount/readdata_cache.h, tests/test_suites/SingleMachineTests/test_helgrind_basic.sh
When performing the read cache memory release, it should be granted that operating over ReadRecords should be protected as expected. This commit ensures that.
=> fix(mount): Fix consistent read cache release

src/master/filesystem_operations.cc, tests/test_suites/ShortSystemTests/test_case_insensitive_filesystem.sh
On the Windows client, the case-insensitive test was failing because the client was not correctly updating the case insensitive flag for a given directory. Also, the test had a line with an incorrect path when checking the proper deletion of files. This commit fixes those issues.
=> fix(mount): Fix case-insensitive test

tests/test_suites/ShortSystemTests/test_auto_recovery_incversion.sh
This commit adds a small sleep right before printing the metadata to
allow the master to dump metadata. This process seems to be slower on
Windows (WSL1) testing, which is why it is needed.
=> fix: Fix test_auto_recovery_incversion (Windows client tests)

doc/CMakeLists.txt, tests/test_suites/SanityChecks/test_generate_manpages.sh
This commit redirects annoying `SyntaxWarning` lines to reduce unnecessary noise in build logs, making them cleaner and easier to debug.
Additionally, a test was added to ensure new `a2x` warnings, such as `SyntaxWarning`, do not return in future builds.
=> fix(build): suppress warnings in manpage generation

cmake/EnvTests.cmake, config.h.in, doc/sfschunkserver.cfg.5.adoc, doc/sfsmaster.cfg.5.adoc, doc/sfsmetalogger.cfg.5.adoc, src/data/sfschunkserver.cfg.in, src/data/sfsmaster.cfg.in, src/data/sfsmetalogger.cfg.in, src/main/main.cc, tests/test_suites/ShortSystemTests/test_limit_glibc_malloc_arenas.sh
The new option LIMIT_GLIBC_MALLOC_ARENAS allows to tune (from configuration) the number of arenas used by malloc in environments with glibc. Setting it to a small positive number like 4 or 8, reduce the virtual memory used by the application, at the cost of possible performance drop for multi-threading (due to contention).
The default is 0, which means disabled (lets glibc decide the values). The options is meant to be used in environments with limited RAM.
So far, the new variable is only used in the daemons: metadata, metalogger and chunkservers.
=> feat: Reduce malloc virtual memory usage

CONTRIBUTING.md
This DCO should ensure that any contribution was made legally under the GPLv3 license and if not, the legal consequences don't fall on the team.
=> chore: Add Developer Certificate of Origin (DCO) to project

tests/tools/valgrind-helgrind.supp
The `ipToString` function was causing a false positive failure during execution of helgrind related test. This change adds a suppresion in order to ignore this issue on the test.
=> test: Add suppression for `ipToString` on mount

src/mount/sauna_client.cc, src/mount/sauna_client.h, src/slogger/slogger.cc
This PR contains two relativetly unrelated changes:
- remove extra endline in some mount debug in some log_debug calls in the mount code. These were the only ones doing it and the log_debug already added a newline after the message, so an empty line was generated.
- support new log options in Windows Client. This change includes removing the automatic flush level at err and defining the default value of the new added options (sfsloglevel and sfslogflushlevel) in the default place. These changes only affect Windows Client code.
=> refactor: Minor logging changes

CMakeLists.txt, cmake/EnvTests.cmake, cmake/HunterGate.cmake, cmake/Libraries.cmake, src/chunkserver/chunkserver-common/disk_chunks.h, src/chunkserver/chunkserver-common/plugin_manager.h, src/chunkserver/disk_chunks_unittest.cc, src/chunkserver/disk_unittest.cc, src/common/platform.h, src/common/small_vector.h, src/common/small_vector_unittest.cc, src/metrics/metrics.cc, src/metrics/metrics.h, src/mount/client/saunafs_c_api.cc, src/tools/file_info.cc, utils/sfs_ping.cc, utils/sfs_pingserv.cc
This change fixes the code snippets used to determine if the functions
std::to_string and std::stoull are available. The previous checks were
failing due to unused results of those functions.
After detecting correctly std::to_string, GCC generated more warnings
related to array-bounds and stringop-overflow. The warnings were
produced by outdated versions of fmt and spdlog (installed from repos).
This PR introduces Hunter as dependency manager to get updated
library versions.
=> fix: Fix functions detection in CMake

src/master/chunks.cc, src/master/filesystem_operations.cc, src/master/filesystem_store.cc, src/master/matotsserv.cc, src/metrics/metrics.cc, src/mount/client/client.cc, src/mount/client/sauna_client_c_linkage.cc, src/mount/client/sauna_client_c_linkage.h, src/mount/global_io_limiter_unittest.cc, src/mount/sauna_client.cc, src/unittests/plan_tester.cc, tests/setup_machine.sh, tests/test_suites/LongSystemTests/test_build_saunafs_using_clang.sh
This pull request ensures that the SaunaFS project can be successfully built with Clang by addressing compatibility issues and suppressing C-linkage errors in the Client API.
**Summary of Changes:**
- Replaced the use of C++-specific types (`std::pair`, `std::vector`) in Client API functions.
- Refactored these functions to return an integer exit code and use references for variable updates.
- Added a Clang build test to validate compatibility and prevent regressions.
- Fix GCC-specific pragmas in Clang builds.
- Removed unused variable assignments in tests to avoid unnecessary warnings.
**Testing:**
- Added a test to validate the SaunaFS build process with Clang.
- Verified the build with both Clang and GCC to ensure no regressions.
=> Build saunafs using clang

src/chunkserver/masterconn.cc, src/protocol/SFSCommunication.h
MATOCS_CHUNKOP and CSTOMA_CHUNKOP are not longer used in the code. This commit removes their remaining references, except for the definitions.
=> chore: Remove unused protocol packets references

src/mount/sauna_client.h
This commit adds an option to enable the status updater thread in the Windows client side in order to manage when to use it or not. The change only affects the Windows client side.
=> feat(mount): Enable status updater thread option
